// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	AccessTokenHash  string
	ExpiresAt        pgtype.Timestamp
	Revoked          pgtype.Bool
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type User struct {
	ID                  uuid.UUID
	Email               string
	PasswordHash        string
	FailedLoginAttempts pgtype.Int4
	LockedUntil         pgtype.Timestamp
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}
