// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id,
  user_id,
  refresh_token_hash,
  access_token_hash,
  expires_at,
  revoked
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, refresh_token_hash, access_token_hash, expires_at, revoked, created_at, updated_at
`

type CreateSessionParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	AccessTokenHash  string
	ExpiresAt        pgtype.Timestamp
	Revoked          pgtype.Bool
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.AccessTokenHash,
		arg.ExpiresAt,
		arg.Revoked,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.AccessTokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSessionByAccessTokenHash = `-- name: FindSessionByAccessTokenHash :one
SELECT id, user_id, refresh_token_hash, access_token_hash, expires_at, revoked, created_at, updated_at FROM sessions WHERE access_token_hash = $1 AND revoked = false
`

func (q *Queries) FindSessionByAccessTokenHash(ctx context.Context, accessTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByAccessTokenHash, accessTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.AccessTokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSessionByRefreshTokenHash = `-- name: FindSessionByRefreshTokenHash :one
SELECT id, user_id, refresh_token_hash, access_token_hash, expires_at, revoked, created_at, updated_at FROM sessions WHERE refresh_token_hash = $1 AND revoked = false
`

func (q *Queries) FindSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.AccessTokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSessionById = `-- name: FindSessionById :one
SELECT id, user_id, refresh_token_hash, access_token_hash, expires_at, revoked, created_at, updated_at FROM sessions WHERE id = $1
`

func (q *Queries) FindSessionById(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.AccessTokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked = true, updated_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked = true, updated_at = NOW() WHERE user_id = $1
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}
