services:
  ## Auth Service
  auth-service:
    build:
      context: ../services/auth
      dockerfile: Dockerfile
    container_name: colloquia-auth-service
    restart: unless-stopped
    env_file:
      - .dev.env
    ports:
      - "8080:8080"
    depends_on:
      auth-db:
        condition: service_healthy

  ## Auth DB
  auth-db:
    image: postgres:16-alpine
    container_name: colloquia-auth-db
    restart: unless-stopped
    env_file:
      - .dev.env
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U colloquia -d colloquia-auth"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  auth-db-data: