// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const batchGetUserProfiles = `-- name: BatchGetUserProfiles :many
SELECT id, email, name, avatar, bio, timezone, status, created_at, updated_at, last_seen_at, language FROM user_profiles WHERE id = ANY($1::uuid[])
`

func (q *Queries) BatchGetUserProfiles(ctx context.Context, dollar_1 []uuid.UUID) ([]UserProfile, error) {
	rows, err := q.db.Query(ctx, batchGetUserProfiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProfile
	for rows.Next() {
		var i UserProfile
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Avatar,
			&i.Bio,
			&i.Timezone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (id, email) VALUES ($1, $2) RETURNING id, email, name, avatar, bio, timezone, status, created_at, updated_at, last_seen_at, language
`

type CreateUserProfileParams struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile, arg.ID, arg.Email)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.Bio,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.Language,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, email, name, avatar, bio, timezone, status, created_at, updated_at, last_seen_at, language FROM user_profiles WHERE id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, id uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.Bio,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.Language,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, avatar, bio, timezone, status, created_at, updated_at, last_seen_at, language FROM user_profiles ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]UserProfile, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProfile
	for rows.Next() {
		var i UserProfile
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Avatar,
			&i.Bio,
			&i.Timezone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, name, avatar, bio, timezone, status, created_at, updated_at, last_seen_at, language FROM user_profiles
WHERE name ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%'
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Column1 pgtype.Text
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]UserProfile, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProfile
	for rows.Next() {
		var i UserProfile
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Avatar,
			&i.Bio,
			&i.Timezone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchLastSeen = `-- name: TouchLastSeen :exec
UPDATE user_profiles SET last_seen_at = NOW() WHERE id = $1
`

func (q *Queries) TouchLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchLastSeen, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles
SET name       = $2,
    avatar     = $3,
    bio        = $4,
    timezone   = $5,
    status     = $6,
    language   = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, avatar, bio, timezone, status, created_at, updated_at, last_seen_at, language
`

type UpdateUserProfileParams struct {
	ID       uuid.UUID
	Name     string
	Avatar   string
	Bio      string
	Timezone string
	Status   string
	Language string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.Avatar,
		arg.Bio,
		arg.Timezone,
		arg.Status,
		arg.Language,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.Bio,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.Language,
	)
	return i, err
}
