// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelMember = `-- name: AddChannelMember :one
INSERT INTO channel_members (channel_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING channel_id, user_id, role, joined_at
`

type AddChannelMemberParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
	Role      string
}

func (q *Queries) AddChannelMember(ctx context.Context, arg AddChannelMemberParams) (ChannelMember, error) {
	row := q.db.QueryRow(ctx, addChannelMember, arg.ChannelID, arg.UserID, arg.Role)
	var i ChannelMember
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const archiveChannel = `-- name: ArchiveChannel :exec
UPDATE channels
SET archived = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ArchiveChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveChannel, id)
	return err
}

const countChannelMembers = `-- name: CountChannelMembers :one
SELECT COUNT(*)::int FROM channel_members
WHERE channel_id = $1
`

func (q *Queries) CountChannelMembers(ctx context.Context, channelID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countChannelMembers, channelID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, description, is_private, type, dm_key, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, is_private, created_by, archived, created_at, updated_at, type, dm_key
`

type CreateChannelParams struct {
	Name        pgtype.Text
	Description string
	IsPrivate   bool
	Type        string
	DmKey       pgtype.Text
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.Description,
		arg.IsPrivate,
		arg.Type,
		arg.DmKey,
		arg.CreatedBy,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.DmKey,
	)
	return i, err
}

const getChannelByDMKey = `-- name: GetChannelByDMKey :one
SELECT id, name, description, is_private, created_by, archived, created_at, updated_at, type, dm_key FROM channels WHERE dm_key = $1 AND type = 'dm'
`

func (q *Queries) GetChannelByDMKey(ctx context.Context, dmKey pgtype.Text) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByDMKey, dmKey)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.DmKey,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, description, is_private, created_by, archived, created_at, updated_at, type, dm_key FROM channels
WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.DmKey,
	)
	return i, err
}

const getChannelMember = `-- name: GetChannelMember :one
SELECT channel_id, user_id, role, joined_at FROM channel_members
WHERE channel_id = $1 AND user_id = $2
`

type GetChannelMemberParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetChannelMember(ctx context.Context, arg GetChannelMemberParams) (ChannelMember, error) {
	row := q.db.QueryRow(ctx, getChannelMember, arg.ChannelID, arg.UserID)
	var i ChannelMember
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listChannelMembers = `-- name: ListChannelMembers :many
SELECT channel_id, user_id, role, joined_at FROM channel_members
WHERE channel_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListChannelMembers(ctx context.Context, channelID uuid.UUID) ([]ChannelMember, error) {
	rows, err := q.db.Query(ctx, listChannelMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMember
	for rows.Next() {
		var i ChannelMember
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChannels = `-- name: ListUserChannels :many
SELECT
    c.id, c.name, c.description, c.is_private, c.created_by, c.archived, c.created_at, c.updated_at, c.type, c.dm_key,
    (SELECT COUNT(*) FROM channel_members m WHERE m.channel_id = c.id)::int AS member_count
FROM channels c
JOIN channel_members cm ON c.id = cm.channel_id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

type ListUserChannelsRow struct {
	ID          uuid.UUID
	Name        pgtype.Text
	Description string
	IsPrivate   bool
	CreatedBy   uuid.UUID
	Archived    bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Type        string
	DmKey       pgtype.Text
	MemberCount int32
}

func (q *Queries) ListUserChannels(ctx context.Context, userID uuid.UUID) ([]ListUserChannelsRow, error) {
	rows, err := q.db.Query(ctx, listUserChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserChannelsRow
	for rows.Next() {
		var i ListUserChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.DmKey,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChannelMember = `-- name: RemoveChannelMember :exec
DELETE FROM channel_members
WHERE channel_id = $1 AND user_id = $2
`

type RemoveChannelMemberParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveChannelMember(ctx context.Context, arg RemoveChannelMemberParams) error {
	_, err := q.db.Exec(ctx, removeChannelMember, arg.ChannelID, arg.UserID)
	return err
}
