// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID          uuid.UUID
	Name        string
	Description string
	IsPrivate   bool
	CreatedBy   uuid.UUID
	Archived    bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type ChannelMember struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
	Role      string
	JoinedAt  pgtype.Timestamp
}
