// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/channels_client.proto

package channelsclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMembershipRequest) Reset() {
	*x = ValidateMembershipRequest{}
	mi := &file_proto_channels_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMembershipRequest) ProtoMessage() {}

func (x *ValidateMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channels_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMembershipRequest.ProtoReflect.Descriptor instead.
func (*ValidateMembershipRequest) Descriptor() ([]byte, []int) {
	return file_proto_channels_client_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateMembershipRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ValidateMembershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ValidateMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMembershipResponse) Reset() {
	*x = ValidateMembershipResponse{}
	mi := &file_proto_channels_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMembershipResponse) ProtoMessage() {}

func (x *ValidateMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channels_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMembershipResponse.ProtoReflect.Descriptor instead.
func (*ValidateMembershipResponse) Descriptor() ([]byte, []int) {
	return file_proto_channels_client_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateMembershipResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

var File_proto_channels_client_proto protoreflect.FileDescriptor

const file_proto_channels_client_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/channels_client.proto\x12\bchannels\"S\n" +
	"\x19ValidateMembershipRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"9\n" +
	"\x1aValidateMembershipResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember2q\n" +
	"\x0eChannelService\x12_\n" +
	"\x12ValidateMembership\x12#.channels.ValidateMembershipRequest\x1a$.channels.ValidateMembershipResponseB#Z!messaging/internal/channelsclientb\x06proto3"

var (
	file_proto_channels_client_proto_rawDescOnce sync.Once
	file_proto_channels_client_proto_rawDescData []byte
)

func file_proto_channels_client_proto_rawDescGZIP() []byte {
	file_proto_channels_client_proto_rawDescOnce.Do(func() {
		file_proto_channels_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_channels_client_proto_rawDesc), len(file_proto_channels_client_proto_rawDesc)))
	})
	return file_proto_channels_client_proto_rawDescData
}

var file_proto_channels_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_channels_client_proto_goTypes = []any{
	(*ValidateMembershipRequest)(nil),  // 0: channels.ValidateMembershipRequest
	(*ValidateMembershipResponse)(nil), // 1: channels.ValidateMembershipResponse
}
var file_proto_channels_client_proto_depIdxs = []int32{
	0, // 0: channels.ChannelService.ValidateMembership:input_type -> channels.ValidateMembershipRequest
	1, // 1: channels.ChannelService.ValidateMembership:output_type -> channels.ValidateMembershipResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_channels_client_proto_init() }
func file_proto_channels_client_proto_init() {
	if File_proto_channels_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_channels_client_proto_rawDesc), len(file_proto_channels_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_channels_client_proto_goTypes,
		DependencyIndexes: file_proto_channels_client_proto_depIdxs,
		MessageInfos:      file_proto_channels_client_proto_msgTypes,
	}.Build()
	File_proto_channels_client_proto = out.File
	file_proto_channels_client_proto_goTypes = nil
	file_proto_channels_client_proto_depIdxs = nil
}
