// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (channel_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, channel_id, user_id, content, created_at
`

type InsertMessageParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
	Content   string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.ChannelID, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesFirst = `-- name: ListMessagesFirst :many
SELECT m.id, m.channel_id, m.user_id, m.content, m.created_at
FROM messages m
WHERE m.channel_id = $1
ORDER BY m.created_at DESC
LIMIT $2
`

type ListMessagesFirstParams struct {
	ChannelID uuid.UUID
	Limit     int32
}

func (q *Queries) ListMessagesFirst(ctx context.Context, arg ListMessagesFirstParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesFirst, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesFromCursor = `-- name: ListMessagesFromCursor :many
SELECT m.id, m.channel_id, m.user_id, m.content, m.created_at
FROM messages m
WHERE m.channel_id = $1
  AND m.created_at < (SELECT m2.created_at FROM messages m2 WHERE m2.id = $2)
ORDER BY m.created_at DESC
LIMIT $3
`

type ListMessagesFromCursorParams struct {
	ChannelID uuid.UUID
	ID        uuid.UUID
	Limit     int32
}

func (q *Queries) ListMessagesFromCursor(ctx context.Context, arg ListMessagesFromCursorParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesFromCursor, arg.ChannelID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
