// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        uuid.UUID
	ChannelID uuid.UUID
	UserID    uuid.UUID
	Content   string
	CreatedAt pgtype.Timestamp
}
