// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/assist.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	CurrentInput  string                 `protobuf:"bytes,2,opt,name=current_input,json=currentInput,proto3" json:"current_input,omitempty"`
	MessageLimit  int32                  `protobuf:"varint,3,opt,name=message_limit,json=messageLimit,proto3" json:"message_limit,omitempty"` // 0 = default (10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuggestionsRequest) Reset() {
	*x = GetSuggestionsRequest{}
	mi := &file_proto_assist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuggestionsRequest) ProtoMessage() {}

func (x *GetSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GetSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_assist_proto_rawDescGZIP(), []int{0}
}

func (x *GetSuggestionsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GetSuggestionsRequest) GetCurrentInput() string {
	if x != nil {
		return x.CurrentInput
	}
	return ""
}

func (x *GetSuggestionsRequest) GetMessageLimit() int32 {
	if x != nil {
		return x.MessageLimit
	}
	return 0
}

type GetSuggestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuggestionsResponse) Reset() {
	*x = GetSuggestionsResponse{}
	mi := &file_proto_assist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuggestionsResponse) ProtoMessage() {}

func (x *GetSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*GetSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_assist_proto_rawDescGZIP(), []int{1}
}

func (x *GetSuggestionsResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_proto_assist_proto protoreflect.FileDescriptor

const file_proto_assist_proto_rawDesc = "" +
	"\n" +
	"\x12proto/assist.proto\x12\x06assist\"\x80\x01\n" +
	"\x15GetSuggestionsRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12#\n" +
	"\rcurrent_input\x18\x02 \x01(\tR\fcurrentInput\x12#\n" +
	"\rmessage_limit\x18\x03 \x01(\x05R\fmessageLimit\":\n" +
	"\x16GetSuggestionsResponse\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestions2`\n" +
	"\rAssistService\x12O\n" +
	"\x0eGetSuggestions\x12\x1d.assist.GetSuggestionsRequest\x1a\x1e.assist.GetSuggestionsResponseB\x14Z\x12assist/internal/pbb\x06proto3"

var (
	file_proto_assist_proto_rawDescOnce sync.Once
	file_proto_assist_proto_rawDescData []byte
)

func file_proto_assist_proto_rawDescGZIP() []byte {
	file_proto_assist_proto_rawDescOnce.Do(func() {
		file_proto_assist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_assist_proto_rawDesc), len(file_proto_assist_proto_rawDesc)))
	})
	return file_proto_assist_proto_rawDescData
}

var file_proto_assist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_assist_proto_goTypes = []any{
	(*GetSuggestionsRequest)(nil),  // 0: assist.GetSuggestionsRequest
	(*GetSuggestionsResponse)(nil), // 1: assist.GetSuggestionsResponse
}
var file_proto_assist_proto_depIdxs = []int32{
	0, // 0: assist.AssistService.GetSuggestions:input_type -> assist.GetSuggestionsRequest
	1, // 1: assist.AssistService.GetSuggestions:output_type -> assist.GetSuggestionsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_assist_proto_init() }
func file_proto_assist_proto_init() {
	if File_proto_assist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_assist_proto_rawDesc), len(file_proto_assist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_assist_proto_goTypes,
		DependencyIndexes: file_proto_assist_proto_depIdxs,
		MessageInfos:      file_proto_assist_proto_msgTypes,
	}.Build()
	File_proto_assist_proto = out.File
	file_proto_assist_proto_goTypes = nil
	file_proto_assist_proto_depIdxs = nil
}
